# Generated by Django 6.0.3 on 2026-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='task',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
