# Generated by Django 6.0.3 on 2026-03-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_created',)},
        ),
    ]
