# Generated by Django 6.0.3 on 2026-03-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='alert_phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='entry',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='task_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
