# Generated by Django 6.0.3 on 2026-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_entry_alert_phone_number_entry_alert_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='task_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
